# This file was generated by GoReleaser. DO NOT EDIT.
cask "fir" do
  name "fir"
  desc "Fast, portable AI coding agent. Single binary, no runtime dependencies."
  homepage "https://github.com/kfet/fir"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/kfet/fir/releases/download/v#{version}/fir-darwin-amd64"
      sha256 "6e39446762f57796909af1a33455bb7d85f7141f00aa9868bd7db7519b30d7f6"
      binary "fir-darwin-amd64", target: "fir"
    end
    on_arm do
      url "https://github.com/kfet/fir/releases/download/v#{version}/fir-darwin-arm64"
      sha256 "26f3c41231e382620e07c555ce0947263ef748746d694f29e0b5a06641b9c403"
      binary "fir-darwin-arm64", target: "fir"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kfet/fir/releases/download/v#{version}/fir-linux-amd64"
      sha256 "33d9379b2069221d40b91616bc8176b3e37f41abb8bf91e97adf7c83ada6d820"
      binary "fir-linux-amd64", target: "fir"
    end
    on_arm do
      url "https://github.com/kfet/fir/releases/download/v#{version}/fir-linux-arm64"
      sha256 "207cd12c360395d6131bc8542b8794d190bc513037bb38c88f14e120f4cc3d49"
      binary "fir-linux-arm64", target: "fir"
    end
  end

  # No zap stanza required
end
