# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fir < Formula
  desc "Fast, portable AI coding agent"
  homepage "https://github.com/kfet/fir"
  version "0.66.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.66.1/fir-darwin-amd64"
      sha256 "db220afd1dcebbc942c4d0e7b46901c6e1185f6d7ed0ab48acf4ec2ea615b35b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.66.1/fir-darwin-arm64"
      sha256 "41dc6ebb5df29a382037efe5b36b42ad0e5a3dd1f1868f3d98a189a0af5404b8"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.66.1/fir-linux-amd64"
      sha256 "f05dd64390de3035289bf8c7385ef598d44b530c4ad3c62dd1e8d10d4ce0b164"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.66.1/fir-linux-armv6"
      sha256 "d14665f10fcdf3639808a6497b31cde33e3e1ca5017cd30f06f8779879015324"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.66.1/fir-linux-arm64"
      sha256 "4c7d4cfa8ac376c2a6eed1a0a1ffce3047ad7b559c96eeb434993169f92bd4ff"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
