# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fir < Formula
  desc "Fast, portable AI coding agent"
  homepage "https://github.com/kfet/fir"
  version "0.61.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.3/fir-darwin-amd64"
      sha256 "e74b0031f6abdcbed2d86450a8c2c43a29f1e899ee03ad48491ad6f0be2ef123"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.3/fir-darwin-arm64"
      sha256 "b8a5958f3b14ec65e3a1818123bcfde04e62f7fae1db31aff8af8b55f86d2454"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.3/fir-linux-amd64"
      sha256 "3dbf9dd45b66cf1beb5f56c102f044b3120fe12af29aa0d1737e4774b39a831d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.3/fir-linux-armv6"
      sha256 "f126b9a9879b9f35b93f085bdd9c94941050b70b5cd829fce2159d08356613e0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.3/fir-linux-arm64"
      sha256 "3a76e19ffad196a3667309614184fc4c1a29e46aa90871c00af19c33f17a3148"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
