# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fir < Formula
  desc "Fast, portable AI coding agent"
  homepage "https://github.com/kfet/fir"
  version "0.31.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.31.0/fir-darwin-amd64"
      sha256 "5ab51a0f483da6ae90451be4d50bf3b51b2ba6ce7e8615c5f6ed74db6c867fe9"

      define_method(:install) do
        bin.install "fir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.31.0/fir-darwin-arm64"
      sha256 "b92b0cf864bc663a93a19ddae48537098f8728d0c8b9cec4edf730b158e80ef3"

      define_method(:install) do
        bin.install "fir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.31.0/fir-linux-amd64"
      sha256 "1400921cf238c0e04e6e0ae824c45b746ea8ea76a9925d990c2c98c3dc0218b8"
      define_method(:install) do
        bin.install "fir"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.31.0/fir-linux-armv6"
      sha256 "186fd0d24b2e175dcaf376b7cfed0d5c818659a755d5ef4fc168a6194868c3cf"
      define_method(:install) do
        bin.install "fir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.31.0/fir-linux-arm64"
      sha256 "819668c0f8cd6cd6b2c2bb08f8301c4385bc2f324da924e07e7f0ddbb9528b5b"
      define_method(:install) do
        bin.install "fir"
      end
    end
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
