# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT046 < Formula
  desc "Fast, portable AI coding agent (pinned 0.46)"
  homepage "https://github.com/kfet/fir"
  version "0.46.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.0/fir-darwin-amd64"
      sha256 "ea40d78399ff31a47fb1ac1819fb26418337361749ecc921f2daeb930da092ca"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.0/fir-darwin-arm64"
      sha256 "147187bab05c06d326a812f8edf71bbfca3a9f8956567d4cf660717ca86d87e2"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.0/fir-linux-amd64"
      sha256 "a61cb53416b3691d0366dfd9e7437e97c1da204ed20ae6d5a01493b8f85ef359"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.0/fir-linux-armv6"
      sha256 "d54b257fdc479f611ba8a9ea7d38fb1b8e4b4d822f472cbd8e0257de9106578d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.0/fir-linux-arm64"
      sha256 "8dbacb9478dd893e4e03b9c97dae1c067c2fa85a411cc0d3bd3de6c8dc5c80f2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.46). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.46

      To go back to the rolling latest:
        brew unlink fir@0.46
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
