# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT046 < Formula
  desc "Fast, portable AI coding agent (pinned 0.46)"
  homepage "https://github.com/kfet/fir"
  version "0.46.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.3/fir-darwin-amd64"
      sha256 "5f5980a41cf90d10224c97bdbf65dd2a9ce8f3c4d6a606a9f57ed3c40da36a21"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.3/fir-darwin-arm64"
      sha256 "3afc4030f9647c4c10027115bf5d94f59e8bb0af9f00b0865275ad5a41cea83b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.3/fir-linux-amd64"
      sha256 "e4cb5070b6a391ffe122b1ad472516f46327f13121f3f9707244f911b91bf191"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.3/fir-linux-armv6"
      sha256 "b7b79dbdc370a6cb6c2e9c37d7982a219c2a0b4950d28c6397296eec8fd91e0b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.3/fir-linux-arm64"
      sha256 "ea610b45655750b427912ff88dd7790c9b6e3cc0a75a5c4774aac153cb288a81"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.46). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.46

      To go back to the rolling latest:
        brew unlink fir@0.46
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
