# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT042 < Formula
  desc "Fast, portable AI coding agent (pinned 0.42)"
  homepage "https://github.com/kfet/fir"
  version "0.42.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.42.0/fir-darwin-amd64"
      sha256 "f7de64dd4e895d00507fc9d073772279713bacb6e56694807d2b5816d2cce2e2"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.42.0/fir-darwin-arm64"
      sha256 "357a0679ae925b7ae33a419ec701941448e7634ee0c549640eef4510e6154479"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.42.0/fir-linux-amd64"
      sha256 "47058d69c98d3310e64475af32f8fc737519caae994fec9de713e37c8f177d5f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.42.0/fir-linux-armv6"
      sha256 "1395d8fcee37ef01a579ca6dfa362f018df5a6f33018eb92c230a511dbdb42e5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.42.0/fir-linux-arm64"
      sha256 "045da5bd8c1fa228261e719022a68d159d2a7ceb310511a66cece3697fff3210"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.42). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.42

      To go back to the rolling latest:
        brew unlink fir@0.42
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
