# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT067 < Formula
  desc "Fast, portable AI coding agent (pinned 0.67)"
  homepage "https://github.com/kfet/fir"
  version "0.67.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.1/fir-darwin-amd64"
      sha256 "ebfb8031e6d0597d37594943a7aa2dbebd8f0d8a273b7bb24207ac9ae81e18fc"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.1/fir-darwin-arm64"
      sha256 "1066dafe302041f971fa3da9c58129d6b231aea12465e3d3455785eebfbc4244"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.1/fir-linux-amd64"
      sha256 "a3669203218cf33861dba889e7b4bf2ef4bf11fc3edd8d26eaecaf36a6553447"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.1/fir-linux-armv6"
      sha256 "5257992df364f26295f4febbd9c4b0fc62b9fe6d677f3608e2a3d05ea991a2d5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.67.1/fir-linux-arm64"
      sha256 "1bc3a9d6be360d6ff8143070134329cb87d2a2443e5988ce652e255025f5c819"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.67). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.67

      To go back to the rolling latest:
        brew unlink fir@0.67
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
