# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT046 < Formula
  desc "Fast, portable AI coding agent (pinned 0.46)"
  homepage "https://github.com/kfet/fir"
  version "0.46.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.4/fir-darwin-amd64"
      sha256 "87656d36609cadaf2081d7474fc88819596e3ab2a150199c8652d03682f165b4"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.4/fir-darwin-arm64"
      sha256 "1315061d6cb7e01b965ee621d5bb0bc1dbe7603b92d4e1023010be0d376a0ad7"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.4/fir-linux-amd64"
      sha256 "c74470c0a03787e9bb406511f3261c8cd6f97a97b3cab0f559bbba9cf0323c16"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.4/fir-linux-armv6"
      sha256 "c6b6b00b306b63326c4ac82d32ed74307c5f751dbd34373a29e97788aeebc94d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.46.4/fir-linux-arm64"
      sha256 "2897472b5814ed19cd88445bef30675b67b5694110878b43f5493891cbd3b69e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.46). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.46

      To go back to the rolling latest:
        brew unlink fir@0.46
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
