# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT044 < Formula
  desc "Fast, portable AI coding agent (pinned 0.44)"
  homepage "https://github.com/kfet/fir"
  version "0.44.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.44.0/fir-darwin-amd64"
      sha256 "2af5bcf381dd489116f36d02bbdd2858eae67e67f0758dce5c6b388b85919b12"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.44.0/fir-darwin-arm64"
      sha256 "c53bf7ebe06d9b3348ce440c12d7a1233867450091b20ed4065db5dda3445180"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.44.0/fir-linux-amd64"
      sha256 "29aada420fd0248dcfefd2d4cb55bcd733aff78adb8da320ad45364709701f99"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.44.0/fir-linux-armv6"
      sha256 "17cf9b4a0e5b86d130a8f5e20330030e53597c1c1d250237554e81997a0a6a8a"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.44.0/fir-linux-arm64"
      sha256 "135ea9e382913981bcc9c719d4f04669a033a1b2b26ab04daebcc18c68b6a622"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.44). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.44

      To go back to the rolling latest:
        brew unlink fir@0.44
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
