# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT069 < Formula
  desc "Fast, portable AI coding agent (pinned 0.69)"
  homepage "https://github.com/kfet/fir"
  version "0.69.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.69.0/fir-darwin-amd64"
      sha256 "a59525eb7b85808bd202f32734f225c1c7c0e6e537765b613956517a836590a4"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.69.0/fir-darwin-arm64"
      sha256 "60a2dc08cb4ca25d7df9f0c1f4f9a3377bf78c804ac57f5533bcb5315341cea5"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.69.0/fir-linux-amd64"
      sha256 "041b1948426dac3f976ba0672d0eb4c954232370f5183a96cf56751d932db4a8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.69.0/fir-linux-armv6"
      sha256 "b6dbe823c2ab3365856b2cfd0b46a98874aff9d12cb56781ecc188f344c03913"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.69.0/fir-linux-arm64"
      sha256 "f37a97bb74a3aaf590513f683b1acc5769a78e50af7d2b81160dbe2111d4890b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.69). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.69

      To go back to the rolling latest:
        brew unlink fir@0.69
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
