# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT039 < Formula
  desc "Fast, portable AI coding agent (pinned 0.39)"
  homepage "https://github.com/kfet/fir"
  version "0.39.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.39.0/fir-darwin-amd64"
      sha256 "c4910a298cf806f40eaf1672919b507b9add2610d612933c4191200ffb0c3535"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.39.0/fir-darwin-arm64"
      sha256 "598dab85e3585cb7bfcc7dba557d733ccfc639570a02b5a9727760077260d713"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.39.0/fir-linux-amd64"
      sha256 "ead33d87d3ebc3150be75a2b0fd8bbf58d9e04224954e35ee74139c474377573"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.39.0/fir-linux-armv6"
      sha256 "b434e8650668993e5ace01ef3a6c1247efc77a0144e690a0610fe145bd149968"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.39.0/fir-linux-arm64"
      sha256 "676293ca9c6792f91a74b4c08e4bed6abf40e206faba797cf70880a62f082324"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.39). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.39

      To go back to the rolling latest:
        brew unlink fir@0.39
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
