# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT054 < Formula
  desc "Fast, portable AI coding agent (pinned 0.54)"
  homepage "https://github.com/kfet/fir"
  version "0.54.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.54.0/fir-darwin-amd64"
      sha256 "1830a2a1d1bada9e2a1590cbf1d24d0a62aeb0abe2cf72050c1a2dde37d819e0"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.54.0/fir-darwin-arm64"
      sha256 "f983c3f06317f636ded10cd018370f2d99d8e3870f12581d8a49dc3825c0472d"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.54.0/fir-linux-amd64"
      sha256 "892a4b9fd73873b571df5fd08d437477651813dacc9d489cb3eddbe24b1980d5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.54.0/fir-linux-armv6"
      sha256 "41806b769645e43b13e9fbacba49aa29f208d110addefd6dbc839e927c9d7747"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.54.0/fir-linux-arm64"
      sha256 "b4e5501562f2ce26ee2a65525d3d50fc2eefd23c674ce99195af5999a539e1c3"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.54). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.54

      To go back to the rolling latest:
        brew unlink fir@0.54
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
