# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT055 < Formula
  desc "Fast, portable AI coding agent (pinned 0.55)"
  homepage "https://github.com/kfet/fir"
  version "0.55.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.55.0/fir-darwin-amd64"
      sha256 "4684a8d25bda363d46e36eb02cbc5fb6bbfb1d6a7de88e084525fcfa9fc71291"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.55.0/fir-darwin-arm64"
      sha256 "d4fe80c72f9176d6a5cdc66327ab79d5f04107720abc66706ee2987f8d472041"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.55.0/fir-linux-amd64"
      sha256 "65cbac12b50c4e2ff92149241d7d7c4b1f93410e1cf8f84ebaf232f96dcf9b56"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.55.0/fir-linux-armv6"
      sha256 "cc4d35311761ed39900f925dc7a1533cf226cd464ffb62c53928884b5fc247ab"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.55.0/fir-linux-arm64"
      sha256 "cfc2345b9f42e81899b596ea90b2fac2018bd477f0d4af58da39b3f69faba77d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.55). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.55

      To go back to the rolling latest:
        brew unlink fir@0.55
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
