# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT043 < Formula
  desc "Fast, portable AI coding agent (pinned 0.43)"
  homepage "https://github.com/kfet/fir"
  version "0.43.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.43.1/fir-darwin-amd64"
      sha256 "fc00157e036090d67432c476e9f9bf7d4337e6d12251eeb29df7e836b3bec6f8"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.43.1/fir-darwin-arm64"
      sha256 "744426973b25bad2eae3239ddafc94273ff161d6073271b1ffd195129a820b74"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.43.1/fir-linux-amd64"
      sha256 "15de15457d98b42c993b26062632338ed6b8f59297f4d658b972e9d1d111dbce"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.43.1/fir-linux-armv6"
      sha256 "37d4023d0b139a37640bd17801ad4c3b318c4446a0e135a0aa01f5faa1f99d9d"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.43.1/fir-linux-arm64"
      sha256 "563db943cabb053bfb18d63762deb2b1b0039772bd89a5602dd03911dbf44a38"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.43). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.43

      To go back to the rolling latest:
        brew unlink fir@0.43
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
