# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT050 < Formula
  desc "Fast, portable AI coding agent (pinned 0.50)"
  homepage "https://github.com/kfet/fir"
  version "0.50.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.1/fir-darwin-amd64"
      sha256 "37ffc7dea4c4a5e16285facaee862d538c9b6ec7233ab50e03060bb2d93eabf1"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.1/fir-darwin-arm64"
      sha256 "cf328c2178c69db39de370cef92554ad497e40a090fab5db5e9165e5482734e9"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.1/fir-linux-amd64"
      sha256 "5a744e0ea576cf837d78f9799f33f9521385572edfe6a5f3b4ad058f5457f2f2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.1/fir-linux-armv6"
      sha256 "02218965acd6523010f8a6179a21a468e5a5c08ce09ab4c6e36429b39121026e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.50.1/fir-linux-arm64"
      sha256 "50190a9a7c8305af882d1ae4ffbdfe93a0c2d8e8c476344e7c0eb2a0356aa9c0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.50). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.50

      To go back to the rolling latest:
        brew unlink fir@0.50
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
