# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT048 < Formula
  desc "Fast, portable AI coding agent (pinned 0.48)"
  homepage "https://github.com/kfet/fir"
  version "0.48.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.48.0/fir-darwin-amd64"
      sha256 "2ac7850b26ba877386abf7072d236c447e349503cc3eb93216bc4ff420fa84fe"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.48.0/fir-darwin-arm64"
      sha256 "0f0cde321b0d1c0cc67fad05cb017a539dd7f8a5086d173c793d26e4f92a7fba"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.48.0/fir-linux-amd64"
      sha256 "50c29fa8b33dafad0bdfd874c0a617177cdd36c082ce4fc5c756a2cd63433648"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.48.0/fir-linux-armv6"
      sha256 "ea577921b1d5cbd2a69ee4985feaece010f389c20fae14d80cd6a6b20a191fa2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.48.0/fir-linux-arm64"
      sha256 "9568e8822d48b388710618c9caee4a45c2d55c12500eea76f2774292f36d8f17"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.48). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.48

      To go back to the rolling latest:
        brew unlink fir@0.48
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
