# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT040 < Formula
  desc "Fast, portable AI coding agent (pinned 0.40)"
  homepage "https://github.com/kfet/fir"
  version "0.40.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.40.0/fir-darwin-amd64"
      sha256 "af52d076dbee7a88a9665e4ecc80a45794228963953729c7038010eb7d1d4aea"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.40.0/fir-darwin-arm64"
      sha256 "8cf56d2aa959cf0a6178f38e20b73cb3a13103c90e6c985ed2a0dd1d0513d1fd"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.40.0/fir-linux-amd64"
      sha256 "e9399c309770d0e3dda434ece0b0c09971f963a87aa8777b5e17e0eadb8f9b2b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.40.0/fir-linux-armv6"
      sha256 "7a9c7a6e7081ef7122dafb2918346753e8fb16cdf971b61d05e6fa376339a9b2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.40.0/fir-linux-arm64"
      sha256 "bd8b933c3ab8cc05679ca9e2dcdf20e4af00baae94182117fd6cacecbaf4bdc3"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.40). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.40

      To go back to the rolling latest:
        brew unlink fir@0.40
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
