# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT068 < Formula
  desc "Fast, portable AI coding agent (pinned 0.68)"
  homepage "https://github.com/kfet/fir"
  version "0.68.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.1/fir-darwin-amd64"
      sha256 "9fc0ab8f61d2cdca660bd5293d2e06e7abfa8b839ddb0531d70fcab723f6843e"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.1/fir-darwin-arm64"
      sha256 "345dcef365b1044c6a8c9338e479d2705c039b5fc5100889d6bf5a6fe2741e78"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.1/fir-linux-amd64"
      sha256 "b179c331b909f1d5a36a0602195e3211c033c6a33ee268000828d233773d0f3c"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.1/fir-linux-armv6"
      sha256 "17a05e9fa7c03e5de9598fce8a654390308c73c4663210aa6c6f540f4f013671"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.1/fir-linux-arm64"
      sha256 "9c59bf0b4d97a37270d63fc1e3d10906211d93a05049f7cd707dc56e7fc32a39"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.68). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.68

      To go back to the rolling latest:
        brew unlink fir@0.68
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
