# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT070 < Formula
  desc "Fast, portable AI coding agent (pinned 0.70)"
  homepage "https://github.com/kfet/fir"
  version "0.70.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.70.0/fir-darwin-amd64"
      sha256 "0d40ae2ed8f0a63893a20ce57f7012cebf836179916e4b8a5ce1d9ea2c6aae18"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.70.0/fir-darwin-arm64"
      sha256 "5def87428e37f14fd755079ccf88694b0f97b899401b1bafc342a12b3b5bd56e"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.70.0/fir-linux-amd64"
      sha256 "1d8aa82e30f0819f1584a655cbb394a62d8285fd63bacac7fda34e0e25e9d3c0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.70.0/fir-linux-armv6"
      sha256 "2a7224bbbdde4b2cb5653ad9ad5da8114c192dd12af6dac25ec9634019388f2b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.70.0/fir-linux-arm64"
      sha256 "5f9f8514d07a98cf3fa888916420656a8cfa307626ee29a7e5a5baeff93810dc"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.70). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.70

      To go back to the rolling latest:
        brew unlink fir@0.70
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
