# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT061 < Formula
  desc "Fast, portable AI coding agent (pinned 0.61)"
  homepage "https://github.com/kfet/fir"
  version "0.61.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.0/fir-darwin-amd64"
      sha256 "516c25cd756ccfdc52e1be8502136b95d1869ee577d3dd9915e7000aba956d5c"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.0/fir-darwin-arm64"
      sha256 "35afedb67047e383aaac74769e5701a376647d0e81016a23d07b42da9585065b"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.0/fir-linux-amd64"
      sha256 "c46f240bb52d04e8f0a162188cff851c7918866b3824a35980b05d46c9789929"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.0/fir-linux-armv6"
      sha256 "d2a843808bcfd9ca20d9315bece6b51a88bc903f85fa7216cd8d9518d0f75c34"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.61.0/fir-linux-arm64"
      sha256 "5936f8388607d41f5137488e1253eccc6a7d343b620b8a8635d915c5f84461e2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.61). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.61

      To go back to the rolling latest:
        brew unlink fir@0.61
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
