# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT072 < Formula
  desc "Fast, portable AI coding agent (pinned 0.72)"
  homepage "https://github.com/kfet/fir"
  version "0.72.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.72.0/fir-darwin-amd64"
      sha256 "4d662a5b2dbb7a14425295357f971ce6a434b02e651c454083bcb727a8796432"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.72.0/fir-darwin-arm64"
      sha256 "ea6f737ad1d9dce010859201e3aad6ab7e903af007c0d314db143576aae85f0c"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.72.0/fir-linux-amd64"
      sha256 "2c3cd13928b2544fd02f64cca796bc880a17a5f31a5dad4aebe1bc0aca5f8455"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.72.0/fir-linux-armv6"
      sha256 "f802c893e7e31eeb336ecb9ee01d78865c9e27c6aa6099ccc36081469f02d058"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.72.0/fir-linux-arm64"
      sha256 "9f51ccfe628c6151facd9b662ddc37de6ebac5e933e223a262a04bd161722974"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.72). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.72

      To go back to the rolling latest:
        brew unlink fir@0.72
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
