# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT064 < Formula
  desc "Fast, portable AI coding agent (pinned 0.64)"
  homepage "https://github.com/kfet/fir"
  version "0.64.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.0/fir-darwin-amd64"
      sha256 "261faab6e750fef5ef9f922c6fe772d08be140f6cd58cd0b266ff0c0b78a76b8"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.0/fir-darwin-arm64"
      sha256 "0021d7db847af8ca5ee878e10a05f9583ab3fdb6d22ed1e797bdaa97877f38ee"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.0/fir-linux-amd64"
      sha256 "4d908c178750991c738e95ad13933fd8ea4c596f26eb804e01d3137998a013d7"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.0/fir-linux-armv6"
      sha256 "86125beb39b61726d2e1ca3914bb80c33e841dbff4403eb29b50b7cc6ecdaa9e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.64.0/fir-linux-arm64"
      sha256 "580663941502e76106ef8390da74b6eb973c12eb0d09bf2c2aa7fdfea5ea10b0"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.64). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.64

      To go back to the rolling latest:
        brew unlink fir@0.64
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
