# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT068 < Formula
  desc "Fast, portable AI coding agent (pinned 0.68)"
  homepage "https://github.com/kfet/fir"
  version "0.68.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.0/fir-darwin-amd64"
      sha256 "ded1f4fd67755f45364baf1dd461c020299db4a4791097a7e4cbbad8a299b8e9"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.0/fir-darwin-arm64"
      sha256 "9e5b0483f9a67f60548fde5ef00907423f8f57d547eb1d7325253b86a28add98"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.0/fir-linux-amd64"
      sha256 "b087674bb5e629b9a84e1cde1f18356b0ec18a5f3d5ad232bd121585596fff0b"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.0/fir-linux-armv6"
      sha256 "b75ea86727eb15e3805e4d1d6bb6a2b28e80f706f2aa8d58cbb86ee4ab5a1477"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.68.0/fir-linux-arm64"
      sha256 "4be644d567567fb7022235f9aa42557c25ea4657567f466196de18d53aba4ef5"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.68). It ships
      its own bin/fir, which collides with the rolling kfet/ai/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.68

      To go back to the rolling latest:
        brew unlink fir@0.68
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
