# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT063 < Formula
  desc "Fast, portable AI coding agent (pinned 0.63)"
  homepage "https://github.com/kfet/fir"
  version "0.63.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.63.0/fir-darwin-amd64"
      sha256 "f15bc4b1c160336b91629d47c4f6d4a4351b9587ca622d33da5179dc5115db46"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.63.0/fir-darwin-arm64"
      sha256 "799e169c0e51cfcba49fa9df0264cbdde14736ad8abb92ef62f5b1356427773a"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.63.0/fir-linux-amd64"
      sha256 "b8179c51058c14ec70425396834d5825b55f802ccd39ee9196c7a766be0af2e8"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.63.0/fir-linux-armv6"
      sha256 "c0bc9614e9e72382e3b1133725bf4d2b7ac72052255929c433d2c54085e8a02e"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.63.0/fir-linux-arm64"
      sha256 "58e1887244ec5fce9e0ba8d76ea44494f025367b533c6509dcd611370d7c27a9"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        chmod 0755, bin/"fir"
        generate_completions_from_executable(bin/"fir", "completion", shells: [:bash, :zsh])
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.63). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.63

      To go back to the rolling latest:
        brew unlink fir@0.63
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
