# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirAT041 < Formula
  desc "Fast, portable AI coding agent (pinned 0.41)"
  homepage "https://github.com/kfet/fir"
  version "0.41.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/fir-dist/releases/download/v0.41.0/fir-darwin-amd64"
      sha256 "d7c8844dc7aacfca74a1b4d2cdfa8dc65919a18fe4961cab46ad2df43cca04f6"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/fir-dist/releases/download/v0.41.0/fir-darwin-arm64"
      sha256 "a2862343a16aaf029973e2528abfbd5813bc49390c16740776a3bfd883701b21"

      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.41.0/fir-linux-amd64"
      sha256 "f866692ebe47bdbf8bb750444cb1c83250bad10ab74314f8f5c6d90ba83630d2"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.41.0/fir-linux-armv6"
      sha256 "9f9a5bec321e59616f745e3ae2268c8521414d169a823506cc56bd482c9b890f"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/fir-dist/releases/download/v0.41.0/fir-linux-arm64"
      sha256 "fe46aa075aca0d510f6a07656613d13521b55f704da4496f53fcebe872e3ec89"
      define_method(:install) do
        bin.install Dir["fir-*"].first => "fir"
        generate_completions_from_executable(bin/"fir", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      This is a pinned channel (fir@0.41). It ships
      its own bin/fir, which collides with the rolling kfet/fir/fir
      formula if you have both installed.

      To switch to this version (e.g. for rollback):
        brew unlink fir 2>/dev/null
        brew link --overwrite fir@0.41

      To go back to the rolling latest:
        brew unlink fir@0.41
        brew link fir
    EOS
  end

  test do
    system "#{bin}/fir", "--version"
  end
end
