# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoeAcpRelay < Formula
  desc "HTTP relay between Poe server bots and ACP-speaking agents"
  homepage "https://github.com/kfet/poe-acp-relay"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.3/poe-acp-relay-darwin-amd64"
      sha256 "71c58bdfc74a93abae02397edbac1e389365717d2da173e918961c5552a215c9"

      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.3/poe-acp-relay-darwin-arm64"
      sha256 "911a324c2c55fae0e17765b2ce6432f131f1d46980b7e8d0d7496da966306862"

      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.3/poe-acp-relay-linux-amd64"
      sha256 "4dc9a1827c550a02a9bd39bb2a55cdb2004ebd905b1792708e4a34557b90ef1b"
      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.3/poe-acp-relay-linux-armv6"
      sha256 "9b65156f6822462fa88c1e353a58d858b75e029f5273445d63cf0316ff323afb"
      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.3/poe-acp-relay-linux-arm64"
      sha256 "195b0c67c01e3ad22829a8de1d56ebb4e304472f6b5ca42337414bd6145d69a7"
      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
  end

  test do
    system "#{bin}/poe-acp-relay", "--version"
  end
end
