# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoeAcpRelay < Formula
  desc "HTTP relay between Poe server bots and ACP-speaking agents"
  homepage "https://github.com/kfet/poe-acp-relay"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.0/poe-acp-relay-darwin-amd64"
      sha256 "abd329b631ad686d117a7fd77038983f33f4bf19a3da6c9dacf4c4b0a6d5f03a"

      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.0/poe-acp-relay-darwin-arm64"
      sha256 "438eb69da57e685d559cdbb7fc6d7eae5384a7fa59196de490309856b00f6b7f"

      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.0/poe-acp-relay-linux-amd64"
      sha256 "ced9ad0809a1489e80e24f4f298235efdbca6f5dea9a0970c9ce4c8427bcc9ae"
      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.0/poe-acp-relay-linux-armv6"
      sha256 "b822b1a6a8f66f85ade7c8cb34f8ec7e18f0d8561914bb6a3d14d6ba5592e3f5"
      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp-relay/releases/download/v0.4.0/poe-acp-relay-linux-arm64"
      sha256 "c1be7fe5bcee00829a34f915990adbb3d1956eb6375869eb3a17c22b11953c0c"
      define_method(:install) do
        bin.install Dir["poe-acp-relay-*"].first => "poe-acp-relay"
      end
    end
  end

  test do
    system "#{bin}/poe-acp-relay", "--version"
  end
end
