# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoeAcp < Formula
  desc "HTTP relay between Poe server bots and ACP-speaking agents"
  homepage "https://github.com/kfet/poe-acp"
  version "0.29.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/poe-acp/releases/download/v0.29.1/poe-acp-darwin-amd64"
      sha256 "55c886dce63874b2f382eba0487ed6ffc22a49e8ee98166f1c220a7cfee6bcf1"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/poe-acp/releases/download/v0.29.1/poe-acp-darwin-arm64"
      sha256 "93f32ce464f8ea3c31cbc5adf6190eb23f83d983eecc173061ca7698866df204"

      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.29.1/poe-acp-linux-amd64"
      sha256 "6fc0071cb2e77d11b4622c0bf5b77c29f0f4518da62f1cd76b652105e988e0af"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.29.1/poe-acp-linux-armv6"
      sha256 "70c7bc210b547892d1b5845bcdbfbdff44887099435256945ad3fe623dd80d6f"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/poe-acp/releases/download/v0.29.1/poe-acp-linux-arm64"
      sha256 "0b163ad1c8520059867a851ce5d92a6c4ede23e99eada74b5f43817a4d886421"
      define_method(:install) do
        bin.install Dir["poe-acp-*"].first => "poe-acp"
      end
    end
  end

  test do
    system "#{bin}/poe-acp", "--version"
  end
end
