# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackAcp < Formula
  desc "Slack bot that relays each thread to a spawned ACP-speaking agent"
  homepage "https://github.com/kfet/slack-acp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.0/slack-acp-darwin-amd64"
      sha256 "4c119c885763f3055c259e41dcac7ca07481798a0eea852b78cf05167d129d7d"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.0/slack-acp-darwin-arm64"
      sha256 "0c13677ee56f7d56055e4e9a647eb4b972d1b0eee528dc6dea412f2aa02f5079"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.0/slack-acp-linux-amd64"
      sha256 "96b9750e8b77e17dbdbaba80e0fc0f4b133f4fb482d98fb1e6dc097f5c534735"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.0/slack-acp-linux-armv6"
      sha256 "79eb0da9950ac0d1ee19c4c1d7c0620dca71a01ba6fa8640c892e609c32e9413"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.0/slack-acp-linux-arm64"
      sha256 "ca554964ca50710f7c6cc77ce1430068ba4f18d8683f77100a1f2c4ff4601cd5"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  test do
    system "#{bin}/slack-acp", "--version"
  end
end
