# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackAcp < Formula
  desc "Slack bot that relays each thread to a spawned ACP-speaking agent"
  homepage "https://github.com/kfet/slack-acp"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.1/slack-acp-darwin-amd64"
      sha256 "eafc3dbcf7f0e179ade300265af4fc18c1eca95813f9a72a34b7a20cc86f3b16"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.1/slack-acp-darwin-arm64"
      sha256 "430cd1199c612be6d1cd6eb2df71d13c3c23fd9097cd0a25e8a1b0496acbf63f"

      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.1/slack-acp-linux-amd64"
      sha256 "4021b49d518657ca6310341be91eab66099fb77c37fcd16d12cd99f154f36cc0"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.1/slack-acp-linux-armv6"
      sha256 "deb78fa6764f5c86f501b9818bf814fb279dfc28cd9f6ed3b7b935ff0311263e"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kfet/slack-acp/releases/download/v0.1.1/slack-acp-linux-arm64"
      sha256 "745993ac5c8d8998f06d2347472bb482791c692cd8295bdbe3360b85db9443ac"
      define_method(:install) do
        bin.install Dir["slack-acp-*"].first => "slack-acp"
      end
    end
  end

  test do
    system "#{bin}/slack-acp", "--version"
  end
end
